DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS tags_users;
DROP TABLE IF EXISTS checks;
DROP TABLE IF EXISTS users_checks;
DROP TABLE IF EXISTS laters;
DROP TABLE IF EXISTS users_laters;
